version: '3.8'
services:

  laravel-docker:
    container_name: laravel-docker
    build: .
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8000:8000